version: 2.1
orbs:
  node: circleci/node@3.0.0
  build-tools: circleci/build-tools@2.7.1
jobs:
  integration-test_merge-parent:
    docker:
      - image: circleci/node:10.20.1
    steps:
      - checkout
      - build-tools/merge-with-parent:
          parent: master
workflows:
  node-tests:
    jobs:
      - integration-test_merge-parent
      - node/test
